# Generated by Django 4.2.15 on 2024-08-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_context_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_context_manager',
            field=models.BooleanField(default=False, verbose_name='Контент-менеджер'),
        ),
    ]
