# Generated by Django 5.0.6 on 2024-06-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_create_at_alter_product_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('inn', models.IntegerField(verbose_name='ИНН')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('phone_number', models.IntegerField(verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
