# Generated by Django 5.0.6 on 2024-06-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='inn',
            field=models.BigIntegerField(verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.BigIntegerField(verbose_name='Номер телефона'),
        ),
    ]
