# Generated by Django 5.0.6 on 2024-07-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активное обращение'),
        ),
    ]
