# Generated by Django 4.2.15 on 2024-08-11 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published', 'Отмена публикации'), ('set_description', 'Изменение описания'), ('set_category', 'Изменение категории')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
