# Generated by Django 5.0.6 on 2024-07-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(default=True, unique=True, verbose_name='признак текущей версии'),
        ),
    ]
